<<<<<<< HEAD
// app/layout.js
import { NextUIProvider } from "@nextui-org/react";
import './globals.css';

export const metadata = {
  title: 'Digital Name Card - Pongwara Jantee',
  description: 'Digital name card for Pongwara Jantee, Managing Director at Bulls Group.',
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> d165c7cfaaa251a60326a6ef1aa8dc5efcbb0a06
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className="antialiased bg-gray-50">
        <NextUIProvider>
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
>>>>>>> d165c7cfaaa251a60326a6ef1aa8dc5efcbb0a06
